GET https://calcmovies.herokuapp.com/api/v1/movies

###
GET https://calcmovies.herokuapp.com/api/v1/movies/5f4bbcf58afec851750359cb
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhbGNAZ21haWwuY29tIiwiaWQiOiI1ZjRiYmNmNThhZmVjODUxNzUwMzU5Y2IiLCJpYXQiOjE1OTkwMjM2NDEsImV4cCI6MTU5OTAyNzI0MX0.gC82_ASUiFgVd0byKRlOupb1JUPa1p0qy5Qxd2ebwGQ

###
POST https://calcmovies.herokuapp.com/api/v1/movies/5f4bbcf58afec851750359cb
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhbGNAZ21haWwuY29tIiwiaWQiOiI1ZjRiYmNmNThhZmVjODUxNzUwMzU5Y2IiLCJpYXQiOjE1OTkwMjM2NDEsImV4cCI6MTU5OTAyNzI0MX0.gC82_ASUiFgVd0byKRlOupb1JUPa1p0qy5Qxd2ebwGQ

{
	"title": "Star Wars",
	"rating": 9
}

###
PUT https://calcmovies.herokuapp.com/api/v1/movies/5f4ecd882645630004007a4e
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhbGNAZ21haWwuY29tIiwiaWQiOiI1ZjRiYmNmNThhZmVjODUxNzUwMzU5Y2IiLCJpYXQiOjE1OTkwMjM2NDEsImV4cCI6MTU5OTAyNzI0MX0.gC82_ASUiFgVd0byKRlOupb1JUPa1p0qy5Qxd2ebwGQ

{
	"rating": 8
}

###
DELETE https://calcmovies.herokuapp.com/api/v1/movies/5f4f3006683f6d00043bfb09
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhbGNAZ21haWwuY29tIiwiaWQiOiI1ZjRiYmNmNThhZmVjODUxNzUwMzU5Y2IiLCJpYXQiOjE1OTkwMjM2NDEsImV4cCI6MTU5OTAyNzI0MX0.gC82_ASUiFgVd0byKRlOupb1JUPa1p0qy5Qxd2ebwGQ

###
POST https://calcmovies.herokuapp.com/api/v1/users/signup
Content-Type: application/json

{
	"name": "Damilola",
	"email": "jamesb@gmail.com",
	"password": "maikel"
}

###
POST https://calcmovies.herokuapp.com/api/v1/users/login
Content-Type: application/json

{
	"email": "jamesb@gmail.com",
	"password": "maikel"
}

###
GET https://calcmovies.herokuapp.com/api/v1/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzYkBnbWFpbC5jb20iLCJpZCI6IjVmNGYzMzg4NjgzZjZkMDAwNDNiZmIwYSIsImlhdCI6MTU5OTAyNjIxMiwiZXhwIjoxNTk5MDI5ODEyfQ.j7vi-AqrdIl2LGMNoKbJ1A_NZMXTNBegF-TF4EhbQZA